### ISSUE TITLE
Question: Where to put my workers?

### ISSUE THREAD

**Issue by uschtwill** [uschtwill/rails_rss_reader#11]
Actually, I am not using that worker anymore. But I had to put it here in order to be picked up. I've seen people keep their workers in `app/workers/`, but that didn't work for me, it didn't get picked up. Is that a gem working its magic for other guys?

![screen shot 2015-03-10 at 17 29 26](https://cloud.githubusercontent.com/assets/10156948/6576913/50657fd6-c74b-11e4-9798-fbfe80eed16a.png)

**Comment by uschtwill** [comment]
@alvinkatojr

**Comment by alvinkatojr** [comment]
@uschtwill there are  bunch of gems that do a good job. I was surprised to see you using a rake task for the background job. By default anything in the app directory will be picked up by rails which is why you see 'workers' folders. 

Try some fun gems, sidekiq, delayed_job are good starters. But before you jump into them read about ActiveJob which is the new plugin for working with jobs and makes work easier.

**Comment by uschtwill** [comment]
@alvinkatojr Alright, will do!
